services:
  web:
    build: .
    container_name: warehouse_web
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - .env
    networks:
      - backend

networks:
  backend:
    external: true