# Generated by Django 5.2.12 on 2026-03-19 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('root', 'Root'), ('chief_storekeeper', 'Chief Storekeeper'), ('storekeeper', 'Storekeeper'), ('observer', 'Observer')], default='storekeeper', max_length=50),
        ),
        migrations.CreateModel(
            name='SyncUserBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('syncserver_user_id', models.UUIDField(blank=True, null=True, unique=True)),
                ('sync_user_token', models.CharField(blank=True, max_length=255)),
                ('sync_role', models.CharField(choices=[('root', 'Root'), ('chief_storekeeper', 'Chief Storekeeper'), ('storekeeper', 'Storekeeper'), ('observer', 'Observer')], default='storekeeper', max_length=50)),
                ('default_site_id', models.CharField(blank=True, max_length=64)),
                ('site_ids', models.JSONField(blank=True, default=list)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('sync_failed', 'Sync Failed')], default='pending', max_length=32)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('token_rotated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sync_binding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
