# Generated by Django 5.2.12 on 2026-03-19 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_role_syncuserbinding'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='syncuserbinding',
            name='last_sync_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='syncuserbinding',
            name='manual_token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncuserbinding',
            name='manual_token_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_sync_token_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='syncuserbinding',
            name='sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('sync_failed', 'Sync Failed'), ('repair_required', 'Repair Required'), ('manual_override', 'Manual Override')], default='pending', max_length=32),
        ),
    ]
