# Generated by Django 5.2.12 on 2026-04-29 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_site_sync_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncDeviceBinding",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("syncserver_device_id", models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ("device_code", models.CharField(max_length=100, unique=True)),
                ("device_name", models.CharField(max_length=255)),
                ("sync_device_token", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("sync_status", models.CharField(choices=[("pending", "Pending"), ("synced", "Synced"), ("sync_failed", "Sync Failed"), ("repair_required", "Repair Required"), ("manual_override", "Manual Override")], default="pending", max_length=32)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_error", models.TextField(blank=True)),
                ("last_sync_payload", models.JSONField(blank=True, default=dict)),
                ("token_rotated_at", models.DateTimeField(blank=True, null=True)),
                ("manual_token_updated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("manual_token_updated_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="manual_sync_device_token_updates", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["device_code"],
            },
        ),
    ]
