# Generated by Django 5.2.12 on 2026-04-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_syncdevicebinding"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="syncdevicebinding",
            options={
                "ordering": ["device_code"],
                "verbose_name": "Устройство SyncServer",
                "verbose_name_plural": "Устройства SyncServer",
            },
        ),
    ]
