# Generated by Django 6.0.3 on 2026-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_syncdevicebinding_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncdevicebinding',
            name='last_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='syncdevicebinding',
            name='sync_device_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='syncuserbinding',
            name='default_site_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='syncuserbinding',
            name='sync_user_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
