# Generated by Django 6.0.3 on 2026-05-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_make_optional_string_fields_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncuserbinding',
            name='last_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
