# Generated by Django 5.2.14 on 2026-06-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_loginattempt_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdevicebinding',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
