# Generated by Django 5.2.14 on 2026-06-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_device_last_seen_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='syncdevicebinding',
            name='sync_state_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='syncdevicebinding',
            name='sync_state_last_seq',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncdevicebinding',
            name='sync_state_behind_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='syncdevicebinding',
            name='health_status',
            field=models.CharField(default='unknown', max_length=32),
        ),
    ]
