# Generated by Django 5.2.16 on 2026-08-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_align_site_mirror_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syncuserbinding',
            name='sync_role',
            field=models.CharField(choices=[('root', 'Root'), ('chief_storekeeper', 'Chief Storekeeper'), ('storekeeper', 'Storekeeper'), ('observer', 'Observer'), ('agent', 'LLM Agent')], default='storekeeper', max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('root', 'Root'), ('chief_storekeeper', 'Chief Storekeeper'), ('storekeeper', 'Storekeeper'), ('observer', 'Observer'), ('agent', 'LLM Agent')], default='storekeeper', max_length=50),
        ),
    ]
