# Generated by Django 5.2.12 on 2026-03-23 04:09

from django.db import migrations, models


def create_postgres_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS catalog_cache_name_trgm_idx "
        "ON catalog_cache_item USING gin (name gin_trgm_ops)"
    )
    schema_editor.execute(
        "CREATE INDEX IF NOT EXISTS catalog_cache_search_text_trgm_idx "
        "ON catalog_cache_item USING gin (search_text gin_trgm_ops)"
    )


def drop_postgres_trigram_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return

    schema_editor.execute("DROP INDEX IF EXISTS catalog_cache_name_trgm_idx")
    schema_editor.execute("DROP INDEX IF EXISTS catalog_cache_search_text_trgm_idx")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogCacheItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=120)),
                ('search_text', models.TextField(blank=True)),
                ('category_id', models.CharField(blank=True, max_length=64)),
                ('category_name', models.CharField(blank=True, max_length=255)),
                ('unit_symbol', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('synced_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'catalog_cache_item',
                'ordering': ['name', 'sync_id'],
                'indexes': [models.Index(fields=['sku'], name='catalog_cache_sku_idx'), models.Index(fields=['category_id'], name='catalog_cache_category_idx'), models.Index(fields=['is_active'], name='catalog_cache_active_idx')],
            },
        ),
        migrations.RunPython(create_postgres_trigram_indexes, drop_postgres_trigram_indexes),
    ]
