# Generated by Django 6.0.3 on 2026-05-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_cache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogcacheitem',
            name='hashtags',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
