# Generated by Django 6.0.3 on 2026-05-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_cache', '0002_catalogcacheitem_hashtags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogcacheitem',
            name='category_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcacheitem',
            name='category_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcacheitem',
            name='search_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcacheitem',
            name='sku',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='catalogcacheitem',
            name='unit_symbol',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
